# Generated by Django 5.1.7 on 2025-04-05 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flete', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportista', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('vencimiento', models.IntegerField()),
                ('nombre_corto', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre_vendedor', models.CharField(max_length=100)),
                ('telefono_vendedor', models.CharField(max_length=20)),
                ('correo_vendedor', models.CharField(max_length=100)),
                ('correo_vendedor2', models.CharField(max_length=100)),
                ('correo_pago', models.CharField(max_length=100)),
                ('tipo_flete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargar.tipoflete')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargar.transporte')),
            ],
        ),
    ]
