# Generated by Django 4.2.18 on 2025-01-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nombre_proveedor', models.CharField(max_length=100)),
                ('vencimiento', models.IntegerField()),
                ('nombre_corto', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=20)),
                ('nombre_vendedor', models.CharField(max_length=100)),
                ('telefono_vendedor', models.CharField(max_length=20)),
                ('correo_vendedor', models.CharField(max_length=100)),
                ('correo_vendedor2', models.CharField(max_length=100)),
                ('correo_pago', models.CharField(max_length=100)),
                ('tipo_flete', models.CharField(max_length=100)),
                ('transporte', models.CharField(max_length=100)),
            ],
        ),
    ]
